name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x
          - 18.x
          - 20.x
          - 22.x

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, Lint & Test
        run: |
          npm i -g npm
          npm i
          npm run lint
          npm test
